# Generated by Django 5.2
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="PerfilProdutor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=150)),
                ("telefone", models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Informe um telefone brasileiro com DDD.", regex="^\\d{10,11}$")])),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("usuario", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="perfil", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Fazenda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=150)), ("cep", models.CharField(max_length=8, validators=[django.core.validators.RegexValidator("^\\d{8}$", "Informe um CEP válido.")])),
                ("estado", models.CharField(max_length=2)), ("cidade", models.CharField(max_length=100)), ("bairro", models.CharField(max_length=120)), ("endereco", models.CharField(blank=True, max_length=255)),
                ("area_hectares", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])), ("quantidade_talhoes", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("culturas", models.JSONField(default=list)),
                ("tipo_cultivo", models.CharField(choices=[("Convencional", "Convencional"), ("Orgânico", "Orgânico Certificado"), ("Agroflorestal", "Agroflorestal"), ("Integrado (ILPF)", "Integrado (ILPF)")], default="Convencional", max_length=30)),
                ("irrigacao", models.CharField(choices=[("Gotejamento", "Gotejamento"), ("Aspersão / Pivô Central", "Aspersão / Pivô Central"), ("Microaspersão", "Microaspersão"), ("Sem Irrigação (Sequeiro)", "Sem Irrigação (Sequeiro)")], default="Gotejamento", max_length=35)),
                ("criada_em", models.DateTimeField(auto_now_add=True)), ("atualizada_em", models.DateTimeField(auto_now=True)),
                ("produtor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fazendas", to=settings.AUTH_USER_MODEL)),
            ], options={"ordering": ["nome"]},
        ),
        migrations.AddConstraint(model_name="fazenda", constraint=models.UniqueConstraint(fields=("produtor", "nome"), name="fazenda_nome_unico_por_produtor")),
    ]
