# Generated by Django 6.1 on 2026-08-26 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaMeteorologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(default='open-meteo', max_length=40)),
                ('coletada_em', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(blank=True, max_length=80)),
                ('dados_atuais', models.JSONField(default=dict)),
                ('dados_horarios', models.JSONField(default=dict)),
                ('dados_diarios', models.JSONField(default=dict)),
                ('dados_solo_modelados', models.JSONField(default=dict)),
                ('dados_brutos', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas_meteorologicas', to='dashboard.fazenda')),
            ],
            options={
                'ordering': ['-coletada_em'],
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cultura', models.CharField(blank=True, max_length=100)),
                ('variedade', models.CharField(blank=True, max_length=100)),
                ('idade_anos', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_solo', models.CharField(blank=True, max_length=100)),
                ('codigo_sensor', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('raio_metros', models.PositiveIntegerField(default=80)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='dashboard.fazenda')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SensorIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_iot', to='dashboard.fazenda')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores_iot', to='dashboard.talhao')),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('done', 'Realizada'), ('cancelled', 'Cancelada')], default='planned', max_length=12)),
                ('produto', models.CharField(max_length=150)),
                ('tipo_insumo', models.CharField(blank=True, max_length=100)),
                ('dose', models.CharField(blank=True, max_length=80)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_aplicacao', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('iea_previsto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='dashboard.fazenda')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes', to='dashboard.talhao')),
            ],
            options={
                'ordering': ['-data_aplicacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacaoJanela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('adequacao', models.PositiveSmallIntegerField()),
                ('classificacao', models.CharField(max_length=30)),
                ('confianca', models.DecimalField(decimal_places=4, max_digits=5)),
                ('decisao', models.CharField(max_length=30)),
                ('fatores', models.JSONField(default=dict)),
                ('riscos', models.JSONField(default=dict)),
                ('qualidade_dados', models.JSONField(default=dict)),
                ('metricas', models.JSONField(default=dict)),
                ('proximas_24h', models.JSONField(default=dict)),
                ('proximas_48h', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='dashboard.coletameteorologica')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='dashboard.fazenda')),
            ],
            options={
                'ordering': ['data', '-adequacao'],
                'indexes': [models.Index(fields=['fazenda', 'data'], name='dashboard_r_fazenda_fbcdc6_idx'), models.Index(fields=['fazenda', 'inicio'], name='dashboard_r_fazenda_1b7f93_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeituraSensorIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida_em', models.DateTimeField()),
                ('umidade_solo', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('dados', models.JSONField(default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='dashboard.sensoriot')),
            ],
            options={
                'ordering': ['-lida_em'],
                'indexes': [models.Index(fields=['sensor', 'lida_em'], name='dashboard_l_sensor__79c8c5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='talhao',
            constraint=models.UniqueConstraint(fields=('fazenda', 'nome'), name='talhao_nome_unico_por_fazenda'),
        ),
        migrations.AddConstraint(
            model_name='sensoriot',
            constraint=models.UniqueConstraint(fields=('fazenda', 'identificador'), name='sensor_identificador_unico_por_fazenda'),
        ),
    ]
