# Generated by Django 6.1 on 2026-08-30 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_talhao_latitude_alter_talhao_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoaplicacao',
            name='quantidade_realizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='execucaoaplicacao',
            name='recomendacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacoes', to='dashboard.recomendacaojanela'),
        ),
        migrations.AlterField(
            model_name='execucaoaplicacao',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejada'), ('confirmed', 'Confirmada'), ('done', 'Realizada'), ('cancelled', 'Cancelada')], default='planned', max_length=12),
        ),
        migrations.CreateModel(
            name='PlanejamentoAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=150)),
                ('tipo_aplicacao', models.CharField(blank=True, max_length=100)),
                ('dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_dose', models.CharField(blank=True, max_length=30)),
                ('data_planejada', models.DateField()),
                ('horario_inicial', models.TimeField(blank=True, null=True)),
                ('horario_final', models.TimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('CONFIRMADA', 'Confirmada'), ('EXECUTADA', 'Executada'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to='dashboard.fazenda')),
                ('recomendacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos', to='dashboard.recomendacaojanela')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos', to='dashboard.talhao')),
            ],
            options={
                'ordering': ['-data_planejada', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='execucaoaplicacao',
            name='planejamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='dashboard.planejamentoaplicacao'),
        ),
    ]
