# Generated by Django 6.1 on 2026-10-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_execucaoaplicacao_quantidade_realizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletameteorologica',
            name='talhao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_meteorologicas', to='dashboard.talhao'),
        ),
        migrations.AddField(
            model_name='recomendacaojanela',
            name='talhao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendacoes', to='dashboard.talhao'),
        ),
    ]
