# Generated by Django 6.1 on 2026-10-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_owner_memberships(apps, schema_editor):
    Fazenda = apps.get_model('dashboard', 'Fazenda')
    MembroFazenda = apps.get_model('dashboard', 'MembroFazenda')
    MembroFazenda.objects.bulk_create([
        MembroFazenda(fazenda_id=farm.pk, usuario_id=farm.produtor_id, funcao='OWNER')
        for farm in Fazenda.objects.all().iterator()
    ], ignore_conflicts=True)


def remove_owner_memberships(apps, schema_editor):
    MembroFazenda = apps.get_model('dashboard', 'MembroFazenda')
    MembroFazenda.objects.filter(funcao='OWNER').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_coletameteorologica_talhao_recomendacaojanela_talhao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(choices=[('MANAGER', 'Gerente'), ('TECHNICIAN', 'Técnico / Agrônomo'), ('EMPLOYEE', 'Funcionário')], max_length=20)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('REVOKED', 'Revogado')], default='PENDING', max_length=12)),
                ('expira_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('convidado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='dashboard.fazenda')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MembroFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('OWNER', 'Proprietário'), ('MANAGER', 'Gerente'), ('TECHNICIAN', 'Técnico / Agrônomo'), ('EMPLOYEE', 'Funcionário')], default='EMPLOYEE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='dashboard.fazenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_fazenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
                'constraints': [models.UniqueConstraint(fields=('fazenda', 'usuario'), name='membro_unico_por_fazenda')],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECOMMENDATION', 'Nova recomendação'), ('PLANNING', 'Novo planejamento'), ('APPLICATION', 'Aplicação registrada'), ('MEMBER', 'Membro adicionado')], max_length=24)),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.CharField(max_length=500)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_fazenda', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_fazenda', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='dashboard.fazenda')),
            ],
            options={
                'ordering': ['-criada_em', '-id'],
                'indexes': [models.Index(fields=['destinatario', 'fazenda', 'lida_em'], name='dashboard_n_destina_a1dfc8_idx')],
            },
        ),
        migrations.RunPython(create_owner_memberships, remove_owner_memberships),
    ]
