# Generated by Django 6.1 on 2026-10-05 14:28

from django.conf import settings
from django.db import migrations, models


def promote_existing_members_and_invitations(apps, schema_editor):
    MembroFazenda = apps.get_model("dashboard", "MembroFazenda")
    ConviteFazenda = apps.get_model("dashboard", "ConviteFazenda")
    MembroFazenda.objects.exclude(funcao="OWNER").update(funcao="OWNER")
    ConviteFazenda.objects.exclude(funcao="OWNER").update(funcao="OWNER")


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_farm_access_and_membership_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            promote_existing_members_and_invitations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='convitefazenda',
            name='funcao',
            field=models.CharField(choices=[('OWNER', 'Proprietário')], default='OWNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='membrofazenda',
            name='funcao',
            field=models.CharField(choices=[('OWNER', 'Proprietário')], default='OWNER', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='convitefazenda',
            constraint=models.CheckConstraint(condition=models.Q(('funcao', 'OWNER')), name='convite_somente_proprietario'),
        ),
        migrations.AddConstraint(
            model_name='membrofazenda',
            constraint=models.CheckConstraint(condition=models.Q(('funcao', 'OWNER')), name='membro_somente_proprietario'),
        ),
    ]
