# Generated by Django 6.1 on 2026-10-05 16:07

from django.conf import settings
from django.db import migrations, models
import dashboard.models
import secrets


def migrate_farm_access_data(apps, schema_editor):
    Fazenda = apps.get_model("dashboard", "Fazenda")
    MembroFazenda = apps.get_model("dashboard", "MembroFazenda")
    database = schema_editor.connection.alias
    alphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
    farms = Fazenda.objects.using(database).all()
    used_codes = set(farms.values_list("codigo_acesso", flat=True))

    for farm in farms.iterator():
        while True:
            code = "GCRP-" + "".join(secrets.choice(alphabet) for _ in range(4))
            code += "-" + "".join(secrets.choice(alphabet) for _ in range(4))
            if code not in used_codes:
                used_codes.add(code)
                break
        Fazenda.objects.using(database).filter(pk=farm.pk).update(codigo_acesso=code)

    memberships = MembroFazenda.objects.using(database).select_related("fazenda")
    for membership in memberships.iterator():
        role = "OWNER" if membership.fazenda.produtor_id == membership.usuario_id else "MEMBER"
        if membership.funcao != role:
            MembroFazenda.objects.using(database).filter(pk=membership.pk).update(funcao=role)


def reverse_migrate_farm_access_data(apps, schema_editor):
    Fazenda = apps.get_model("dashboard", "Fazenda")
    MembroFazenda = apps.get_model("dashboard", "MembroFazenda")
    database = schema_editor.connection.alias
    alphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
    used_codes = set()

    for farm in Fazenda.objects.using(database).all().iterator():
        while True:
            code = "GC-" + "".join(secrets.choice(alphabet) for _ in range(8))
            if code not in used_codes:
                used_codes.add(code)
                break
        Fazenda.objects.using(database).filter(pk=farm.pk).update(codigo_acesso=code)

    MembroFazenda.objects.using(database).exclude(funcao="OWNER").update(funcao="OWNER")


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_convitefazenda_funcao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='convitefazenda',
            name='convite_somente_proprietario',
        ),
        migrations.RemoveConstraint(
            model_name='membrofazenda',
            name='membro_somente_proprietario',
        ),
        migrations.AlterField(
            model_name='membrofazenda',
            name='funcao',
            field=models.CharField(choices=[('OWNER', 'Proprietário'), ('MEMBER', 'Membro')], default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='codigo_acesso',
            field=models.CharField(default=dashboard.models.generate_farm_access_code, editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='culturas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            migrate_farm_access_data,
            reverse_migrate_farm_access_data,
        ),
        migrations.AddConstraint(
            model_name='membrofazenda',
            constraint=models.CheckConstraint(condition=models.Q(('funcao__in', ['OWNER', 'MEMBER'])), name='membro_funcao_valida'),
        ),
        migrations.DeleteModel(
            name='ConviteFazenda',
        ),
    ]
