# Generated by Django 6.1 on 2026-10-06 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_convitefazenda_convite_somente_proprietario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessado_em', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_sistema', to='dashboard.fazenda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acessado_em', '-id'],
                'indexes': [models.Index(fields=['-acessado_em'], name='dashboard_a_acessad_167914_idx')],
            },
        ),
    ]
