# Generated by Django 6.1 on 2026-10-07 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_acessosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('horario_inicial', models.TimeField(blank=True, null=True)),
                ('horario_final', models.TimeField(blank=True, null=True)),
                ('dia_inteiro', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('APLICACAO', 'Aplicação'), ('PLANTIO', 'Plantio'), ('COLHEITA', 'Colheita'), ('ADUBACAO', 'Adubação'), ('IRRIGACAO', 'Irrigação'), ('PULVERIZACAO', 'Pulverização'), ('MANEJO', 'Manejo'), ('INSPECAO', 'Inspeção'), ('MANUTENCAO', 'Manutenção'), ('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('REUNIAO', 'Reunião'), ('VISITA_TECNICA', 'Visita técnica'), ('TAREFA', 'Tarefa'), ('OUTRO', 'Outro')], default='TAREFA', max_length=20)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('USUARIO', 'Criado pelo usuário'), ('RECOMENDACAO', 'Recomendação GoldCrop')], default='USUARIO', max_length=20)),
                ('quantidade_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidade_produto', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='dashboard.execucaoaplicacao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario_criados', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='dashboard.fazenda')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='dashboard.produto')),
                ('recomendacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='dashboard.recomendacaojanela')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='dashboard.talhao')),
            ],
            options={
                'ordering': ['data', 'dia_inteiro', 'horario_inicial', 'id'],
                'indexes': [models.Index(fields=['fazenda', 'data'], name='dashboard_e_fazenda_063da3_idx'), models.Index(fields=['fazenda', 'categoria', 'data'], name='dashboard_e_fazenda_beb561_idx')],
            },
        ),
    ]
