# Generated by Django 6.1 on 2026-10-06 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0011_acessosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100, verbose_name='Identificação/Brinco')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome/Apelido')),
                ('tipo', models.CharField(choices=[('LEITE', 'Gado Leiteiro'), ('CORTE', 'Gado de Corte'), ('MISTO', 'Misto'), ('OUTRO', 'Outro')], default='LEITE', max_length=20, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('VACA_LACTACAO', 'Vaca em lactação'), ('VACA_SECA', 'Vaca seca'), ('NOVILHA', 'Novilha'), ('BEZERRA', 'Bezerra'), ('BEZERRO', 'Bezerro'), ('TOURO', 'Touro')], max_length=50, verbose_name='Categoria')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('raca', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('origem', models.CharField(blank=True, max_length=150, verbose_name='Origem')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('VENDIDO', 'Vendido'), ('MORTO', 'Morto'), ('TRANSFERIDO', 'Transferido'), ('OUTRO', 'Outro')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('arquivado', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='dashboard.fazenda')),
                ('mae', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_mae', to='pecuaria.animal')),
                ('pai', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_pai', to='pecuaria.animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['identificacao'],
            },
        ),
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimento', models.CharField(max_length=100, verbose_name='Tipo de Alimento')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Consumida')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade')),
                ('data', models.DateField(verbose_name='Data do Consumo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes_pecuaria', to='dashboard.fazenda')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentacoes_pecuaria', to='dashboard.produto')),
                ('animal', models.ForeignKey(blank=True, help_text='Deixe em branco para lote/geral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentacoes', to='pecuaria.animal')),
            ],
            options={
                'verbose_name': 'Registro de Alimentação',
                'verbose_name_plural': 'Registros de Alimentação',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('VACINACAO', 'Vacinação'), ('MEDICAMENTO', 'Medicamento'), ('VERMIFUGACAO', 'Vermifugação'), ('DOENCA', 'Doença'), ('TRATAMENTO', 'Tratamento'), ('PESAGEM', 'Pesagem'), ('PARTO', 'Parto'), ('INSEMINACAO', 'Inseminação'), ('DIAGNOSTICO_GESTACAO', 'Diagnóstico de Gestação'), ('SECAGEM', 'Secagem'), ('ALTERACAO_CATEGORIA', 'Alteração de Categoria'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dosagem', models.CharField(blank=True, max_length=100, verbose_name='Dosagem')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='pecuaria.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos_pecuaria', to='dashboard.fazenda')),
                ('produto_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manejos_pecuaria', to='dashboard.produto')),
            ],
            options={
                'verbose_name': 'Registro de Manejo',
                'verbose_name_plural': 'Registros de Manejo',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProducaoLeite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Produção')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade de Litros')),
                ('ordenha', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('UNICA', 'Única')], default='UNICA', max_length=20, verbose_name='Ordenha')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producoes_leite', to='pecuaria.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes_leite', to='dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Produção de Leite',
                'verbose_name_plural': 'Produções de Leite',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Reproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSEMINACAO', 'Inseminação'), ('MONTA', 'Monta'), ('DIAGNOSTICO', 'Diagnóstico de Gestação'), ('GESTACAO', 'Gestação Confirmada'), ('PARTO', 'Parto'), ('ABORTO', 'Aborto'), ('SECAGEM', 'Secagem')], max_length=50, verbose_name='Tipo de Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('touro_inseminador', models.CharField(blank=True, max_length=150, verbose_name='Touro/Sêmen')),
                ('data_estimada_parto', models.DateField(blank=True, null=True, verbose_name='Data Estimada do Parto')),
                ('status_gestacao', models.CharField(blank=True, choices=[('PENDENTE', 'Aguardando Diagnóstico'), ('CONFIRMADA', 'Confirmada'), ('NEGATIVA', 'Negativa/Falha'), ('CONCLUIDA', 'Concluída (Parto/Aborto)')], max_length=20, verbose_name='Status da Gestação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducoes', to='pecuaria.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducoes_pecuaria', to='dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Registro de Reprodução',
                'verbose_name_plural': 'Registros de Reprodução',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['fazenda', 'status', 'categoria'], name='pecuaria_an_fazenda_121621_idx'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('fazenda', 'identificacao'), name='pecuaria_animal_id_unico_por_fazenda'),
        ),
        migrations.AddIndex(
            model_name='alimentacao',
            index=models.Index(fields=['fazenda', '-data'], name='pecuaria_al_fazenda_cd7e21_idx'),
        ),
        migrations.AddIndex(
            model_name='alimentacao',
            index=models.Index(fields=['produto', '-data'], name='pecuaria_al_produto_e5eceb_idx'),
        ),
        migrations.AddIndex(
            model_name='manejo',
            index=models.Index(fields=['fazenda', '-data'], name='pecuaria_ma_fazenda_41a0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='manejo',
            index=models.Index(fields=['animal', '-data'], name='pecuaria_ma_animal__0ad087_idx'),
        ),
        migrations.AddIndex(
            model_name='producaoleite',
            index=models.Index(fields=['fazenda', '-data'], name='pecuaria_pr_fazenda_1925e5_idx'),
        ),
        migrations.AddIndex(
            model_name='producaoleite',
            index=models.Index(fields=['animal', '-data'], name='pecuaria_pr_animal__6d86ce_idx'),
        ),
        migrations.AddIndex(
            model_name='reproducao',
            index=models.Index(fields=['fazenda', '-data'], name='pecuaria_re_fazenda_edd533_idx'),
        ),
        migrations.AddIndex(
            model_name='reproducao',
            index=models.Index(fields=['animal', '-data'], name='pecuaria_re_animal__d0038d_idx'),
        ),
        migrations.AddIndex(
            model_name='reproducao',
            index=models.Index(fields=['fazenda', 'data_estimada_parto'], name='pecuaria_re_fazenda_97676c_idx'),
        ),
    ]
