# Generated by Django 6.1 on 2026-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecuaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejo',
            name='quantidade_produto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade de produto utilizado'),
        ),
    ]
